"""Generated campaign equipment, not a claim of availability in every map."""

CAMPAIGN_SHA256 = 'df1767547db06e2539563bcd49ad2f818109c385d56481209339795024c9371d'
EQUIPMENT = (
    {'code': 'brpb', 'name': '生锈板甲靴', 'description': '普通靴子\n\n+1点力量\n+10移动速度\n\n这双靴子历经漫长路途，岁月痕迹清晰可见。', 'slot': 'Boots', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'eaba', 'name': '铁匠围裙', 'description': '精良护甲\n\n+8点力量\n+10%斗志\n\n永远不要低估铁匠的力量或决心。', 'slot': 'Chest', 'chapters': ['UndeadRE01_02']},
    {'code': 'eabh', 'name': '古老青铜盔', 'description': '精良头盔\n\n+100点生命值\n+1点护甲\n\n岁月褪去了它的光泽，却依旧坚固堪用。', 'slot': 'Head', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'easc', 'name': '血色十字军护甲', 'description': '精良护甲\n\n+6点生命恢复效果\n+3点力量\n装备：针对穿戴者的基础攻击有33%几率为穿戴者恢复10点生命值。\n\n浸染着血色十字军的坚韧信念。', 'slot': 'Chest', 'chapters': ['UndeadRE02']},
    {'code': 'eash', 'name': '阿古斯的呆滞之手', 'description': '精良副手武器\n\n+3%生命窃取\n+5%致命一击几率\n\n这只手干枯的掌心摸起来仍有余温——让人想起阿古斯曾如何温柔地将爱妻玛利亚拥入怀中。', 'slot': 'Offhand', 'chapters': ['UndeadRE01_02']},
    {'code': 'eauc', 'name': '拿不走的蜡烛', 'description': '绝对是传说级饰品！\n\n你拿走了蜡烛。你为什么要拿蜡烛？本该留在那儿的，你本该置之不理的。可你偏不，就是要拿，拿了一样又一样。你不是狗头人，你不懂蜡烛有多重要。对你来说，这不过又是一件亮闪闪的玩意儿罢了。哼，你拿了这么多宝贝，说不定下一次，黑暗就会把你也吞噬。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'eavr', 'name': '吸血法袍', 'description': '稀有护甲\n\n+10%生命窃取\n+10%闪避\n\n采用上等丝绸织就，衣料深处织入了黑暗嗜血的附魔。', 'slot': 'Chest', 'chapters': ['UndeadRE02']},
    {'code': 'ebcs', 'name': '骸骨指挥官之颅', 'description': '稀有头盔\n\n+5点智力\n+5点生命恢复效果\n装备：获得扭曲之骨光环，使附近友方非英雄单位的攻击速度和移动速度提升25%。\n\n骷髅战士相比血肉同类的一大优势，便是没有肌腱的骨骼能以迅捷而出人意料的方式活动。', 'slot': 'Head', 'chapters': ['UndeadRE03a']},
    {'code': 'ebdg', 'name': '刃舞者胫甲', 'description': '精良靴子\n\n+1点护甲\n+6%攻击速度\n\n这双深色皮靴是决斗者和刺客的绝佳选择。', 'slot': 'Boots', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ebdw', 'name': '死亡行者', 'description': '稀有靴子\n\n+4点敏捷\n+3点智力\n+20移动速度\n\n穿上这双铁靴之人，便如死神一般势不可挡。', 'slot': 'Boots', 'chapters': ['UndeadRE02']},
    {'code': 'ebnp', 'name': '通灵师的瘟疫胫甲', 'description': '精良靴子\n\n+5点技能伤害\n+20移动速度\n装备：攻击佩戴者的敌人会感染致命疫病，在4秒内每秒受到2点法术伤害。\n\n这双靴子被黑暗魔法浸染，走到哪里，就会把瘟疫带到哪里。', 'slot': 'Boots', 'chapters': ['UndeadRE01']},
    {'code': 'eboc', 'name': '腐化之刃', 'description': '稀有主手武器\n\n+7点力量\n+25%暴击伤害\n装备：你的基础攻击会降低命中敌人的护甲3点，持续5秒。\n\n此利刃不仅撕裂血肉，更会绞碎那些不幸被其锋芒扫过之人的灵魂。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'ebof', 'name': '被遗忘者之靴', 'description': '精良靴子\n\n+3点生命恢复效果\n+6%法术暴击几率\n\n一双为被遗忘者特制的靴子，用以帮助那些双脚在腐烂过程中未能完好留存下来的亡者。', 'slot': 'Boots', 'chapters': ['UndeadRE01_03', 'UndeadRE02']},
    {'code': 'eboh', 'name': '海拉的束缚', 'description': '史诗手套\n\n+2点敏捷\n+2点智力\n+10%技能增强\n装备：每隔40秒，你的下一次基础攻击会向命中目标发出一道强大的缓慢波动，对直线上的所有命中敌人造成400点法术伤害。\n\n海拉，这位海巫兼维库人的冥界女王，派出她的克瓦迪尔军队沿海劫掠，将卑劣的灵魂拖入她的领域。', 'slot': 'Gloves', 'chapters': ['UndeadRE03a']},
    {'code': 'eboi', 'name': '踏冰者之靴', 'description': '稀有靴子\n\n+5点力量\n+20移动速度\n装备：你的基础攻击有8%（暴击时12%）几率喷出一道寒霜波，造成40点初始法术伤害，并在3秒内每秒造成额外5点法术伤害。\n\n穿上这双靴子之人，能在地面轻盈滑行，仿佛身处冰封之湖。', 'slot': 'Boots', 'chapters': ['UndeadRE01']},
    {'code': 'ebom', 'name': '食人魔法师护腕', 'description': '史诗手套\n\n+10%攻击速度\n+10%法术暴击几率\n装备：你的基础攻击可对自身施放治疗波，或对命中目标施放闪电链，几率均为10%（暴击时25%）。两种魔法会分别弹跳至附近的友方或敌方单位，治疗或造成100点伤害，最多影响3个目标，每次弹跳效果衰减15%。\n\n食人魔的魔法向来如同其使用者一般，混乱无常、难以捉摸。', 'slot': 'Gloves', 'chapters': ['UndeadRE02_04']},
    {'code': 'ebos', 'name': '霸主马靴', 'description': '精良靴子\n\n+3点力量\n+1点护甲\n\n无数溃不成军的敌人都葬身于这双靴子之下。', 'slot': 'Boots', 'chapters': ['UndeadRE01', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ebr1', 'name': '黑石链甲头盔', 'description': '史诗头盔\n\n+15%致命一击几率\n+15%暴击伤害\n+3点护甲\n\n黑石氏族以厚重甲胄和彪悍战力闻名，是入侵东部王国最令人畏惧的兽人部族之一。', 'slot': 'Head', 'chapters': ['UndeadRE02_03']},
    {'code': 'ebr2', 'name': '剑圣巨剑', 'description': '史诗主手武器\n\n+12%致命一击几率\n+12%暴击伤害\n+12点敏捷\n\n此剑曾由雷德·黑手执掌，在恶魔献祭仪式中沾染了邪秽之力。', 'slot': 'Primary', 'chapters': ['UndeadRE02_03']},
    {'code': 'ebrp', 'name': '黑石钢板甲', 'description': '史诗护甲\n\n+8点护甲\n+12点力量\n\n这件兽人护甲由黑石氏族锻造，能承受惊人伤害。', 'slot': 'Chest', 'chapters': ['UndeadRE02']},
    {'code': 'ebsc', 'name': '血色十字军战靴', 'description': '稀有靴子\n\n+2点护甲\n+2点力量\n+2点智力\n\n蕴藏着血色十字军的正义信念。', 'slot': 'Boots', 'chapters': ['UndeadRE02']},
    {'code': 'ebsp', 'name': '血色圣骑士胸甲', 'description': '稀有护甲\n\n+5点力量\n+5点智力\n+5点护甲\n\n这件护甲被打磨得在晨光中熠熠生辉，正是虔诚圣骑士所需的力量和虔信的化身。', 'slot': 'Chest', 'chapters': ['UndeadRE02_06']},
    {'code': 'ebwb', 'name': '灾厄散播者之靴', 'description': '精良靴子\n\n+4点智力\n+3点技能伤害\n\n这双靴子那沾染污渍的皮革上，仍残留着前任主人的恶臭。', 'slot': 'Boots', 'chapters': ['UndeadRE01_02']},
    {'code': 'ecbr', 'name': '寒冰召唤者之握', 'description': '稀有手套\n\n+8%致命一击几率\n+3%生命窃取\n装备：你的基础攻击有8%（暴击时20%）几率对目标施放冰霜新星，对主目标造成50点法术伤害，并对命中目标150范围内的所有敌方单位造成50点额外伤害，同时将其冻结3秒。\n\n这双手套由诺森德冰冻苔原的维库人铁匠打造，能汲取空气中的热量。', 'slot': 'Gloves', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ecdc', 'name': '惊惧胸甲', 'description': '精良护甲\n\n+5点攻击力\n+3点敏捷\n装备：赋予穿戴者吸血光环，使附近友方近战单位获得4%生命窃取。\n\n纳斯雷兹姆所穿的服饰，令洛丹伦的平民畏惧不已。', 'slot': 'Chest', 'chapters': ['UndeadRE01']},
    {'code': 'ecgb', 'name': '卫兵靴子', 'description': '普通靴子\n\n+2点敏捷\n\n采用精钢和皮革打造，曾经有人穿着它踏遍了都城的每一条街道。', 'slot': 'Boots', 'chapters': ['UndeadRE01']},
    {'code': 'ecgc', 'name': '卫兵胸甲', 'description': '普通护甲\n\n+50点生命值\n+1点护甲\n\n一件制作精良的护甲，为都城守卫所穿戴。', 'slot': 'Chest', 'chapters': ['UndeadRE01']},
    {'code': 'ecgh', 'name': '卫兵头盔', 'description': '普通头盔\n\n+1点护甲\n\n都城守卫佩戴的头盔。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'ecgr', 'name': '诅咒金戒', 'description': '稀有饰品\n\n+15%致命一击几率\n+15%暴击伤害\n+-2点护甲\n\n强大的力量总要付出惨痛的代价。', 'slot': 'Ring', 'chapters': ['UndeadRE01_03']},
    {'code': 'ech1', 'name': '血色之心法杖', 'description': '史诗主手武器\n\n+15%技能增强\n+8点生命恢复效果\n装备：你施放的法术有25%几率以你为中心引发鲜血爆炸，对附近敌方单位造成150点法术伤害。\n\n这支古老法杖赋予持有者掌控禁忌血魔法的能力，让他们得以窃取对手的生命力。', 'slot': 'Primary', 'chapters': ['UndeadRE03a']},
    {'code': 'ech2', 'name': '血色之心利刃', 'description': '史诗副手武器\n\n+16%攻击速度\n+16%致命一击几率\n装备：你的基础攻击打出致命一击时会造成额外50点法术伤害，并为你恢复25点生命值。\n\n这把华美的利刃浸染着血魔法，在夺取受害者性命的同时治愈持有者。', 'slot': 'Offhand', 'chapters': ['UndeadRE03a']},
    {'code': 'ech3', 'name': '血色之心守护者', 'description': '史诗护甲\n\n+12%致命一击几率\n+12%法术暴击几率\n+8%生命窃取\n+8%技能汲取\n\n这件护甲有着非自然的心跳，将自身力量加持给穿戴者。', 'slot': 'Chest', 'chapters': ['UndeadRE03a']},
    {'code': 'ecig', 'name': '不朽守护者胸甲', 'description': '稀有护甲\n\n+8点护甲\n\n曾由一座古老神殿的坚毅守护者所穿戴。他在世之时，从未放任何入侵者踏入神殿半步。', 'slot': 'Chest', 'chapters': ['UndeadRE02_04', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ecrn', 'name': '通灵侍僧的赤玉石', 'description': '史诗饰品\n\n+15%法术暴击几率\n+10%技能汲取\n\n最好别问这颗玉石为何会散发如此独特的赤红光芒。', 'slot': 'Ring', 'chapters': ['UndeadRE02_06']},
    {'code': 'ecrr', 'name': '再生之戒', 'description': '普通饰品\n\n+2点生命恢复效果\n\n这枚戒指的核心散发出一股舒缓的暖意。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'ecss', 'name': '精钢长剑', 'description': '普通主手武器\n\n+5点攻击力\n\n一把手感均衡但外表普通的长剑。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'edbb', 'name': '死亡使者之靴', 'description': '稀有靴子\n\n+5点力量\n+5点技能伤害\n装备：针对穿戴者的攻击者会感染死亡使者瘟疫，持续10秒，每秒受到8点法术伤害。\n\n由死亡骑士穿戴，他们踏足之处，死亡与腐朽便蔓延开来。', 'slot': 'Boots', 'chapters': ['UndeadRE03a']},
    {'code': 'edbs', 'name': '枯竭的血石', 'description': '稀有饰品\n\n+7点生命恢复效果\n装备：你的基础攻击为附近的最多4个友方单位恢复5点生命值。\n\n尽管真正的力量已被抽干，这颗血石潜藏的魔力仍能为持有者带来助益。', 'slot': 'Ring', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'edbw', 'name': '深海魔袋', 'description': '稀有饰品\n（为佩戴者提供一个额外技能）\n\n粉碎波浪\n发出一道巨浪，对一条直线上的每个敌方地面单位造成175点伤害，最多造成1050点总伤害。（冷却时间：20秒）\n\n这个袋子封存着汹涌的潮汐，开启时便会奔涌而出。', 'slot': 'Trinket', 'chapters': ['UndeadRE02_02']},
    {'code': 'edrb', 'name': '黑暗游侠护腕', 'description': '稀有手套\n\n+4点敏捷\n+10%攻击速度\n装备：你的基础攻击有12%（暴击时25%）几率召唤一名被遗忘者女妖为你作战，持续16秒。\n\n这副护腕专为精灵的手臂量身定制，在提供防护的同时，丝毫不影响黑暗游侠的灵巧身手。', 'slot': 'Gloves', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'edrc', 'name': '黑暗游侠胸甲', 'description': '稀有护甲\n\n+8点敏捷\n+8%技能增强\n装备：获得黑暗指挥官光环，提升附近友方非英雄单位的伤害5。\n\n黑暗游侠由希尔瓦娜斯·风行者亲自训练，深受所有被遗忘者士兵的敬重。', 'slot': 'Chest', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'edrh', 'name': '黑暗游侠兜帽', 'description': '稀有头盔\n\n+6点敏捷\n+6%技能速度\n装备：你施放的法术有30%几率召唤一名被遗忘者女妖为你作战，持续16秒。\n\n潜行于林间、出手毫不留情的黑暗游侠，都会佩戴这顶兜帽。', 'slot': 'Head', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'edrs', 'name': '黑暗游侠之影', 'description': '稀有靴子\n\n+3点敏捷\n+10%魔法抗性\n装备：获得黑暗女王光环，使附近友方单位的攻击速度和移动速度提升10%。\n\n黑暗游侠熟知荒野地形，能引领同伴踏上无人察觉的隐秘路径。', 'slot': 'Boots', 'chapters': ['UndeadRE02_02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'edts', 'name': '亵渎塔盾', 'description': '精良副手武器\n\n+10%魔法抗性\n+1点护甲\n\n从都城废墟中回收而来，经重制后供被遗忘者的亡灵卫兵使用。', 'slot': 'Offhand', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'edwg', 'name': '恶魔战刃', 'description': '稀有主手武器\n\n+5点敏捷\n+5%闪避\n+10%致命一击几率\n装备：你的近战基础攻击会造成顺劈效果，将造成伤害的15%转嫁给附近敌方单位。\n\n这是卡多雷强大而可怖的恶魔猎手的标志性武器。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'eefr', 'name': '无尽恢复药水', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n恢复\n使目标单位在10秒内恢复300点生命值和100点法力值。（冷却时间：30秒）\n\n一瓶取之不尽的恢复药剂，源自炼金术研究的重大突破。', 'slot': 'Trinket', 'chapters': ['UndeadRE02']},
    {'code': 'eeh1', 'name': '次级工程护目镜', 'description': '精良头盔\n\n+8%技能速度\n+20移动速度\n\n一件简易头部装备，能为佩戴者提供微薄的增益。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'eeh2', 'name': '高级工程护目镜', 'description': '稀有头盔\n\n+15%技能速度\n+30移动速度\n\n一件品质上乘的头部装备，能让复杂操作变得轻松许多。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'eeh3', 'name': '大师级工程护目镜', 'description': '史诗头盔\n\n+20%技能速度\n+40移动速度\n+5点智力\n\n一件大师级头部装备，深受艾泽拉斯最顶尖的工程师们推崇和青睐。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'eeit', 'name': '附魔铭文工具', 'description': '稀有饰品\n\n+5点智力\n+12%法术暴击几率\n\n以细心和精准打造，专为需要兼具二者之人而作。', 'slot': 'Ring', 'chapters': ['UndeadRE01_02']},
    {'code': 'eerc', 'name': '废墟之城锋刃', 'description': '史诗主手武器\n\n+10点力量\n+30%暴击伤害\n装备：你的基础攻击会降低命中敌人的护甲5点，持续5秒。\n\n这把恐怖的战斧采用亡者的血肉铸成，总是向往着死亡和毁灭的去处。', 'slot': 'Primary', 'chapters': ['UndeadRE03a']},
    {'code': 'eesq', 'name': '蜘蛛女王精华', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n蜘蛛女王精华\n英雄获得8点额外攻击力和15%生命窃取。\n持续12秒。（冷却时间：30秒）\n\n蜘蛛女王致命而狂暴的精华，经提取提纯后供战士使用。', 'slot': 'Trinket', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'efch', 'name': '被遗忘者勇士头盔', 'description': '精良头盔\n\n+5点生命恢复效果\n+3点力量\n\n头戴此物者，象征着对被遗忘者的忠诚。', 'slot': 'Head', 'chapters': ['UndeadRE01', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'efgc', 'name': '疯狂食尸鬼之爪', 'description': '稀有手套\n\n+16%攻击速度\n+3%生命窃取\n\n将疯狂食尸鬼体内的狂怒释放出来。', 'slot': 'Gloves', 'chapters': ['UndeadRE03b']},
    {'code': 'efgh', 'name': '血肉魔像主胸腔', 'description': '精良护甲\n\n+280点生命值\n\n由骸骨和血肉重塑而成的混杂护甲。', 'slot': 'Chest', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'efla', 'name': '脆弱皮甲', 'description': '普通护甲\n\n+4点敏捷\n+20点生命值\n\n粗糙破旧，却总好过毫无防护。', 'slot': 'Chest', 'chapters': ['UndeadRE02']},
    {'code': 'efpb', 'name': '被遗忘者瘟疫弓', 'description': '精良主手武器\n\n+3点生命恢复效果\n+5点敏捷\n+10%法术暴击几率\n\n一把威力强大的弓，无论施放法术还是射出箭矢都精准无比。', 'slot': 'Primary', 'chapters': ['UndeadRE01_03', 'UndeadRE02']},
    {'code': 'egcg', 'name': '十字军护手', 'description': '精良手套\n\n+3点力量\n+2点智力\n\n这副手甲专为施展神圣魔法和发挥武技之力而打造。', 'slot': 'Gloves', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'egdb', 'name': '死亡使者护手', 'description': '稀有手套\n\n+12%致命一击几率\n+10%斗志\n\n精锐死亡骑士在执行主人命令时穿戴。', 'slot': 'Gloves', 'chapters': ['UndeadRE03a']},
    {'code': 'egfg', 'name': '被遗忘者护手', 'description': '精良手套\n\n+8%攻击速度\n+2点生命恢复效果\n\n被遗忘者铁匠打造，用于守卫幽暗城。', 'slot': 'Gloves', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'eggp', 'name': '凤凰手套', 'description': '精良手套\n\n+10%技能增强\n装备：你施放的法术有10%几率灼伤自己，造成40点法术伤害。\n\n这双手套燃烧着狂烈的怒火，根本无法掌控火焰。', 'slot': 'Gloves', 'chapters': ['UndeadRE01_05']},
    {'code': 'egns', 'name': '静谧金项链', 'description': '史诗饰品\n\n+200点生命值\n+70%法力恢复效果\n装备：施放法术时恢复50点生命值。\n\n这条华丽的项链专为达拉然的法师议会官员打造，用以增强施法者的耐力。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'egop', 'name': '完美护手', 'description': '稀有手套\n\n+2所有属性\n+7%闪避\n\n这副手套工艺完美无瑕，戴在任何人手上都贴合无间。', 'slot': 'Gloves', 'chapters': ['UndeadRE01']},
    {'code': 'egow', 'name': '荒野之赐', 'description': '精良饰品\n\n+2所有属性\n+2点生命恢复效果\n\n这颗巨大的种子被藤蔓和荆棘层层包裹，保护着它缓慢而恒久地生长。', 'slot': 'Ring', 'chapters': ['UndeadRE01_03']},
    {'code': 'egsb', 'name': '巨型骷髅骸骨', 'description': '精良主手武器\n\n-10%攻击速度\n+18点攻击力\n装备：你的基础攻击有10%几率造成额外25点伤害，并使命中目标昏迷2秒。\n\n临时凑合用用，总比手无寸铁要强。', 'slot': 'Primary', 'chapters': ['UndeadRE01_02']},
    {'code': 'egsc', 'name': '血色十字军手套', 'description': '精良手套\n\n+1点护甲\n+3点智力\n\n蕴藏着血色十字军的狂热意志。', 'slot': 'Gloves', 'chapters': ['UndeadRE02']},
    {'code': 'egwh', 'name': '豺狼人督军皮甲', 'description': '精良护甲\n\n+2点护甲\n+4点敏捷\n\n众所周知，豺狼人会鞣制人皮来搭建帐篷。看来有位颇有胆识的制皮匠决定以其人之道还治其人之身。', 'slot': 'Chest', 'chapters': ['UndeadRE01_03']},
    {'code': 'ehbm', 'name': '强盗面罩', 'description': '精良头盔\n\n+6点敏捷\n\n那些想要效仿声名鹊起的迪菲亚兄弟会的人，都会戴上这种面罩。', 'slot': 'Head', 'chapters': ['UndeadRE01_02', 'UndeadRE02']},
    {'code': 'ehcf', 'name': '勇猛巨型黄水晶', 'description': '稀有饰品\n\n+8点力量\n+10%技能速度\n\n一位野心勃勃的珠宝匠原本想制作一枚戒指，结果打造出了这条项链。', 'slot': 'Ring', 'chapters': ['UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ehco', 'name': '机遇绯红头盔', 'description': '稀有头盔\n\n+4点敏捷\n+4点智力\n+4%致命一击几率\n+4%法术暴击几率\n\n绝不要浪费对手露出的任何破绽。', 'slot': 'Head', 'chapters': ['UndeadRE02']},
    {'code': 'ehgh', 'name': '吉尔尼斯头饰', 'description': '精良头盔\n\n+4点攻击力\n+3点力量\n装备：获得统御光环，使附近友方单位的攻击力提高8%。\n\n吉尔尼斯的服饰很少出现在格雷迈恩之墙外。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'ehhi', 'name': '大检察官头饰', 'description': '史诗头盔\n\n+65%法力恢复效果\n+6点智力\n装备：获得奉献光环，让900范围内的友方单位每秒恢复3点生命值。\n\n大检察官统领着血色十字军的神职人员，指引他们惩处邪恶，将亡灵之灾从洛丹伦彻底净化。', 'slot': 'Head', 'chapters': ['UndeadRE02']},
    {'code': 'ehig', 'name': '铁卫士头盔', 'description': '稀有头盔\n\n+3点护甲\n+7%魔法抗性\n装备：每15秒可抵挡一次敌方对英雄施放的减益法术。\n\n头盔上镌刻的符文能削弱敌方魔法对佩戴者的影响。', 'slot': 'Head', 'chapters': ['UndeadRE01_05']},
    {'code': 'ehls', 'name': '迷失的幽魂号角', 'description': '稀有副手武器\n\n+7%技能汲取\n装备：你施放的法术为附近的最多4个友方单位恢复12点生命值。\n\n这只象牙号角收容着四处寻觅归处的迷失幽魂。', 'slot': 'Offhand', 'chapters': ['UndeadRE02']},
    {'code': 'ehol', 'name': '湖泊之心', 'description': '稀有头盔\n\n+10%技能速度\n+4点智力\n装备：获得辉煌光环，每秒为附近友方单位提升0.5点法力恢复效果。\n\n这颗海蓝宝石周身环绕着流转不息的水波，戴在头上便化作一顶华美的王冠。', 'slot': 'Head', 'chapters': ['UndeadRE02_04']},
    {'code': 'ehph', 'name': '海盗帽', 'description': '稀有头盔\n\n+5%致命一击几率\n+3所有属性\n\n咱们去大肆劫掠吧！', 'slot': 'Head', 'chapters': ['UndeadRE02_02']},
    {'code': 'ehrl', 'name': '霜领之盔', 'description': '稀有头盔\n\n+10%技能速度\n+10%斗志\n装备：你施放的法术有12%几率引发冰霜新星砸向地面，对附近敌方单位造成100点法术伤害，并使其减速25%，持续4秒。\n\n游荡在诺森德遥远大陆上的亡魂，掌控着冰雪之力。', 'slot': 'Head', 'chapters': ['UndeadRE02']},
    {'code': 'ehsc', 'name': '血色队长头盔', 'description': '稀有头盔\n\n+3点护甲\n+10%致命一击几率\n\n由血色十字军狂热无畏的队长们佩戴。', 'slot': 'Head', 'chapters': ['UndeadRE02_06']},
    {'code': 'ehsh', 'name': '白银之手战锤', 'description': '精良主手武器\n\n+5点攻击力\n+5点智力\n装备：你的基础攻击为你恢复5点生命值，并有10%几率造成额外25点伤害，使命中目标昏迷2秒。\n\n这是白银之手骑士团被阿尔萨斯王子解散前，骑士们所使用的神圣武器。', 'slot': 'Primary', 'chapters': ['UndeadRE01_06']},
    {'code': 'ehtc', 'name': '高阶圣殿征服者战甲', 'description': '史诗护甲\n\n+5所有属性\n+20%斗志\n装备：你的基础攻击会为穿戴者恢复15点生命值。\n\n每一场胜利，圣光都会为高阶圣殿骑士注入力量，护佑血色十字军薪火相传。', 'slot': 'Chest', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ehtf', 'name': '高阶圣殿烈焰手甲', 'description': '史诗手套\n\n+5点力量\n+15%攻击速度\n装备：你的基础攻击会为目标叠加圣殿火焰，每次攻击的伤害都会比上一次提升3点。受此效果影响的敌方单位死亡时，会在神圣烈焰中爆炸，造成50点法术伤害。\n\n与高阶圣殿为敌者，终将被圣焰吞噬。', 'slot': 'Gloves', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ehtj', 'name': '高阶圣殿之裁决', 'description': '史诗主手武器\n\n+8点力量\n+8点智力\n+15%攻击速度\n装备：你的基础攻击有15%（暴击时25%）几率向命中目标施放一道圣光波，对路径上的所有敌人造成75点伤害。\n\n这把高阶圣殿骑士的专属武器以圣焰锻造，将神圣的裁决降临于所有与圣光为敌者。', 'slot': 'Primary', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ehtm', 'name': '高阶圣殿之靴', 'description': '史诗靴子\n\n+5点力量\n+40移动速度\n装备：每12秒可抵挡一次针对穿戴者的敌方法术。\n\n无人能阻挡高阶圣殿骑士踏遍洛丹伦荒芜之地的步伐。', 'slot': 'Boots', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'ehtv', 'name': '高阶圣殿骑士面甲', 'description': '史诗头盔\n\n+4点力量\n+4点智力\n+2点护甲\n装备：你的基础攻击有5%（暴击时10%）几率对自身施放心灵之火，攻击力提升20%，护甲提升3点，持续60秒。\n\n血色十字军的高阶圣殿骑士，身具远超凡俗的圣光美德。', 'slot': 'Head', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'eicc', 'name': '冰冠戒指', 'description': '史诗饰品\n\n+3点护甲\n+200点法力值\n装备：针对佩戴者的攻击有8%几率在攻击者处触发冰霜新星，对目标造成60点法术伤害，并对150范围内所有附近敌人造成额外60点法术伤害。所有命中的敌人还会被冻结4秒。\n\n在冰冠冰川中，巫妖王端坐于冰封王座之上，统领着他的亡灵大军。', 'slot': 'Ring', 'chapters': ['UndeadRE03a']},
    {'code': 'eicd', 'name': '冰寒钻石', 'description': '稀有饰品\n\n+12%法力值效率\n+10%法术暴击几率\n\n一经触碰，这颗钻石便会施放出致命寒冰魔法。', 'slot': 'Ring', 'chapters': ['UndeadRE03a']},
    {'code': 'eigc', 'name': '感染的食尸鬼符咒', 'description': '稀有饰品\n（为佩戴者提供一个额外技能）\n\n召唤感染的食尸鬼\n召唤-个感染的食尸鬼为你战斗，持续12秒。它们会使用感染利爪攻击，使受到该减益影响的单位死亡后额外召唤2个感染的食尸鬼。持续6秒。（冷却时间：30秒）\n\n这枚符咒中的死灵魔法会吸引食尸鬼，并驱使它们服从持有者的命令。', 'slot': 'Trinket', 'chapters': ['UndeadRE01']},
    {'code': 'ejjr', 'name': '锯齿青玉戒指', 'description': '精良饰品\n\n+100点生命值\n+10%致命一击几率\n+5%暴击伤害\n\n这枚戒指的宝石边缘锋利无比，足以破皮见血。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'ekmg', 'name': '卡多雷月刃', 'description': '史诗主手武器\n\n+25%攻击速度\n+20%致命一击几率\n装备：你的基础攻击打出致命一击时，会向附近一名敌方单位掷出月刃，造成75点物理伤害。月刃会继续弹跳至附近敌人，每次弹跳的伤害降低20%，总共命中3个目标。\n\n这是卡多雷哨兵的专属武器。一万年来，她们一直守护着灰谷森林，抵御入侵者。', 'slot': 'Primary', 'chapters': ['UndeadRE03a']},
    {'code': 'ekmh', 'name': '狗头人采矿头盔', 'description': '精良头盔\n\n+4力量\n+1护甲\n装备：携带时可提升英雄在夜晚的视野范围。\n\n狗头人把蜡烛顶在头上不是为了看得更清，而是为了驱散黑暗。', 'slot': 'Head', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'elfq', 'name': '遗失的被遗忘者箭袋', 'description': '稀有饰品\n（为佩戴者提供一个额外技能）\n\n召唤被遗忘者游侠\n召唤2个被遗忘者游侠为你作战，持续30秒。（冷却时间：30秒）\n\n仅凭这支箭袋中的一支箭，便能标记目标，让黑暗游侠们毫不留情地追杀到底。', 'slot': 'Trinket', 'chapters': ['UndeadRE02_02']},
    {'code': 'elmf', 'name': '次级被遗忘者印记', 'description': '普通饰品\n（为佩戴者提供一个额外技能）\n\n凋零缠绕\n发射一股死亡能量，可为友方亡灵单位恢复150点生命值，或对敌方生命单位造成一半的伤害。（冷却时间：15秒）\n\n这枚小小的徽记，承载着被遗忘者的苦难与荣光。', 'slot': 'Trinket', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'elod', 'name': '黎明长枪', 'description': '稀有主手武器\n\n+12%致命一击几率\n+12%法术暴击几率\n装备：你的基础攻击会造成额外12点法术伤害。\n\n一支配得上真正英雄的荣耀长枪。', 'slot': 'Primary', 'chapters': ['UndeadRE02_04']},
    {'code': 'emcg', 'name': '鱼人装扮手套', 'description': '精良手套\n\n+2点敏捷\n+4%法力值效率\n\n粗劣的盗版，其原型更糙。至少这双手套是防水的。', 'slot': 'Gloves', 'chapters': ['UndeadRE01_02']},
    {'code': 'emof', 'name': '被遗忘者手稿', 'description': '稀有饰品\n（为佩戴者提供一个额外技能）\n\n召唤亡灵卫兵\n召唤3名亡灵卫兵为你作战，持续30秒。（冷却时间：30秒）\n\n这份宣言于幽暗城建立之初写就，勾勒出被遗忘者新生王国的核心纲领。', 'slot': 'Trinket', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'emrw', 'name': '变异鼠的鞭尾', 'description': '精良副手武器\n\n+4点敏捷\n+3点技能伤害\n装备：你的基础攻击会使命中的敌方单位中毒，每秒造成6点伤害，并降低其攻击和移动速度15%，持续4秒。\n\n这条尾巴长得诡异，也同样令人作呕，即便脱离了本体仍在不停抽搐。', 'slot': 'Offhand', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'emto', 'name': '神秘曙光猫眼石', 'description': '稀有饰品\n\n+10%法术暴击几率\n+6点智力\n\n这颗强大的宝石会在曙光初见时释放出全部魔法潜能。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'eobb', 'name': '白骨圆盾', 'description': '普通副手武器\n\n+1点护甲\n+2点力量\n\n比木质坚固，比金属廉价，是战争时期的充足战备物资。', 'slot': 'Offhand', 'chapters': ['UndeadRE01']},
    {'code': 'eocs', 'name': '破损盾牌', 'description': '普通副手武器\n\n+1点护甲\n装备：受到的基础攻击伤害降低2。\n\n这面盾牌已布满伤痕，或许曾救下过某人的性命。', 'slot': 'Offhand', 'chapters': ['UndeadRE01']},
    {'code': 'eofs', 'name': '碎裂头骨', 'description': '普通副手武器\n\n+4%技能增强\n\n这个倒霉的家伙被斧头劈中了头颅，如今他的头骨有了新的用处。', 'slot': 'Offhand', 'chapters': ['UndeadRE01']},
    {'code': 'eoms', 'name': '孔雀石短剑', 'description': '精良副手武器\n\n+6点敏捷\n装备：你的基础攻击有15%几率使命中目标失明8秒，降低其击中几率33%。\n\n剑柄护手处镶嵌的宝石熠熠生辉，常会反射光线，晃花直视者的双眼。', 'slot': 'Offhand', 'chapters': ['UndeadRE02']},
    {'code': 'eops', 'name': '方阵护盾', 'description': '精良副手武器\n\n+100点生命值\n装备：提升250范围内友方单位的护甲2点。\n\n正如所有方阵战法一样，唯有与盟友并肩作战时，这面盾牌才能发挥真正的威力。', 'slot': 'Offhand', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'eosc', 'name': '血色十字军之盾', 'description': '史诗副手武器\n\n+10%法力值效率\n+3点护甲\n装备：针对持有者的攻击有25%几率为持有者恢复20点生命值。\n\n这面盾牌由血色十字军锻造并赐福，为持有者带来慰藉和庇护。', 'slot': 'Offhand', 'chapters': ['UndeadRE02_02']},
    {'code': 'epah', 'name': '憎恶之钩', 'description': '精良主手武器\n\n+5点力量\n+5%生命窃取\n\n刚清洗干净，等待下一次钩扯。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'epbc', 'name': '疫病使者胸甲', 'description': '精良护甲\n\n+5点生命恢复效果\n+2点技能伤害\n装备：穿戴者周围笼罩着一团疾病之云，感染附近的敌方生命单位，持续12秒。受感染的单位每秒受到2点伤害。\n\n采用从憎恶身上切割下来的部件打造而成的护甲，虽粗糙但实用。', 'slot': 'Chest', 'chapters': ['UndeadRE01_03', 'UndeadRE02']},
    {'code': 'epdb', 'name': '破晓者', 'description': '史诗主手武器\n\n+18%致命一击几率\n+18%法术暴击几率\n装备：每隔9秒，你的下一次基础攻击会在敌人脚下召唤烈焰风暴，在3秒内对附近敌人造成总计240点伤害。\n\n这把巨剑的剑柄散发着太阳光辉，照射在敌人身上，将他们付之一炬。', 'slot': 'Primary', 'chapters': ['UndeadRE02_04']},
    {'code': 'epdw', 'name': '亡语者', 'description': '稀有主手武器\n\n+12点攻击力\n+12%技能增强\n\n据说丧命于这把利刃之下的人，会听见暗影国度彼岸的低语。', 'slot': 'Primary', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'epfc', 'name': '食尸鬼之爪', 'description': '精良主手武器\n\n+24%攻击速度\n装备：被你的基础攻击命中的敌人护甲减少2点，持续5秒。\n\n饥饿的食尸鬼能将利爪直刺受害者的心脏。', 'slot': 'Primary', 'chapters': ['UndeadRE02_02']},
    {'code': 'ephf', 'name': '巨型链枷', 'description': '精良主手武器\n\n-10%攻击速度\n+15%致命一击几率\n装备：你的基础攻击打出暴击时会施放次级战争践踏，对附近敌方单位造成25点伤害并使其昏迷1秒。\n\n一件巨型武器，舍弃精巧技法，只求纯粹蛮力。', 'slot': 'Primary', 'chapters': ['UndeadRE01_03']},
    {'code': 'epmb', 'name': '莫格莱尼的力量', 'description': '主手武器\n\n+8点力量\n+7点攻击力\n装备：你的近身基础攻击会造成顺劈效果，将造成伤害的15%转嫁给附近敌方单位。\n\n这柄巨锤曾由雷诺·莫格莱尼所持，向所有亵渎洛丹伦的人降下正义的惩罚。', 'slot': 'Primary', 'chapters': ['UndeadRE02']},
    {'code': 'epmm', 'name': '修道院钉锤', 'description': '稀有主手武器\n\n+25%攻击速度\n+5点智力\n装备：你的基础攻击可为附近的最多4个友方单位恢复8点生命值。\n\n执此兵刃者，当守护无辜，肃清邪恶。', 'slot': 'Primary', 'chapters': ['UndeadRE01', 'UndeadRE01_02', 'UndeadRE01_03', 'UndeadRE01_05', 'UndeadRE01_06', 'UndeadRE02_04', 'UndeadRE02_06', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'epmw', 'name': '凡俗法杖', 'description': '普通主手武器\n\n+7%技能增强\n\n一根带有微弱魔力的简易法杖。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'epoa', 'name': '可疑合剂', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n剧毒之云\n向目标敌方单位投掷一瓶药剂，溢出的毒气会影响周围的敌方单位，降低其移动速度25%，并使其攻击有25%的未命中率，持续12秒。（冷却时间：30秒）\n\n从制作原料来看，这瓶药剂与其喝下去，不如扔出去更有用。', 'slot': 'Trinket', 'chapters': ['UndeadRE01']},
    {'code': 'epqp', 'name': '采石镐', 'description': '精良主手武器\n\n+5点力量\n+5点攻击力\n装备：你的基础攻击有15%几率造成25点额外伤害，并使目标昏迷1秒。\n\n这是被遗忘者劳工常用的简易武器。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'eprm', 'name': '原始魔法之戒', 'description': '精良饰品\n\n+4点智力\n+3点技能伤害\n\n这枚朴素的戒指采用破旧的皮革碎片制成，用两颗小水獭獠牙穿缀固定。', 'slot': 'Ring', 'chapters': ['UndeadRE01_02']},
    {'code': 'epsb', 'name': '骸骨之弓', 'description': '稀有主手武器\n\n+15%致命一击几率\n+20%攻击速度\n\n黑暗游侠们一直争论不休：到底哪种生物的骨头，才最适合用来制弓。', 'slot': 'Primary', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'epsc', 'name': '磨利斩斧', 'description': '稀有主手武器\n\n+24点攻击力\n\n一把锋利的斩斧，趁手好用。', 'slot': 'Primary', 'chapters': ['UndeadRE02_04', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'epsg', 'name': '幽魂之地长剑', 'description': '稀有主手武器\n\n+12点攻击力\n+10%法力值效率\n装备：你的基础攻击有10%（暴击时15%）几率施放恐惧嚎叫，降低附近敌方单位的3点护甲和20%攻击力，持续5秒。\n\n奎尔萨拉斯以南便是幽魂之地，这是一片饱受诅咒的森林区域，阿尔萨斯初次入侵该王国时，曾在此开辟出一条毁灭之路。', 'slot': 'Primary', 'chapters': ['UndeadRE02_02']},
    {'code': 'epsh', 'name': '白银之手守护者', 'description': '稀有副手武器\n\n+2点护甲\n+3点智力\n装备：针对持有者的攻击有12%几率重击攻击者，造成40点法术伤害并使其昏迷2秒。\n\n这面盾牌刻有白银之手徽记，专为恪守圣骑士信条的人打造。', 'slot': 'Offhand', 'chapters': ['UndeadRE01_06']},
    {'code': 'epwb', 'name': '疫铸·灾厄化身', 'description': '史诗主手武器\n\n+12%致命一击几率\n+12%法术暴击几率\n+12点技能伤害\n装备：你的基础攻击会使命中的敌人中毒5秒，并使其攻击速度和移动速度降低20%，并每秒造成10点伤害。此外，每隔12数秒你的下一次基础攻击会召唤腐臭蝠群，对锥形范围内的所有命中敌人造成160点法术伤害。\n\n这把利刃最初由天灾军团打造，用以在洛丹伦散播瘟疫，如今被遗忘者用它来对付昔日的黑暗之主。', 'slot': 'Primary', 'chapters': ['UndeadRE02']},
    {'code': 'epws', 'name': '彩绘木剑', 'description': '普通主手武器\n\n+3点攻击力\n+3%攻击速度\n\n即便只是孩童的玩具，落入合适的人手中也能成为武器。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'eraf', 'name': '狂热之戒', 'description': '普通饰品\n\n+1点生命恢复效果\n+5%攻击速度\n\n上面镶嵌着一颗如鲜血般殷红的宝石。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'erbg', 'name': '生锈的铜护手', 'description': '普通手套\n\n+1点护甲\n\n这副手甲由新手铁匠打造，早已完成了它的使命。', 'slot': 'Gloves', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'ercs', 'name': '囚笼之魂', 'description': '精良饰品\n\n+3点技能伤害\n+5%法力值效率\n\n一个狂怒的灵魂被囚禁在笼中，迫切渴望重获自由。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'eref', 'name': '亡者回响', 'description': '稀有饰品\n\n+5点智力\n+10%技能速度\n\n骄阳之下，敌军已然突破防线。落魄的血之子啊，他们正步步紧逼。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'eres', 'name': '土灵徽记', 'description': '史诗饰品\n\n+6点护甲\n装备：针对佩戴者的攻击有5%几率施放战争践踏，造成50点伤害并使附近敌方单位昏迷3秒。\n\n作为矮人的先祖，土灵是由泰坦塑造的石质造物，为践行泰坦的宏伟蓝图而生。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'erfa', 'name': '幸运冒险者之戒', 'description': '普通饰品\n\n+2%致命一击几率\n+1所有属性\n\n好运总是眷顾勇者。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'ergg', 'name': '贪婪之赐', 'description': '精良饰品\n\n+5点攻击力\n+5%攻击速度\n装备：你对敌方非英雄单位的基础攻击，会将造成伤害的一小部分转化为金币。\n\n追求财富和追求胜利，往往本就是同一件事。', 'slot': 'Ring', 'chapters': ['UndeadRE02_01']},
    {'code': 'ergm', 'name': '强效法力效率之戒', 'description': '稀有饰品\n\n+15%法力值效率\n装备：你施放的法术会返还5点法力值。\n\n这枚白金指环上镶嵌着一颗法力宝石，能够吸收并重新分配佩戴者消耗的法力。', 'slot': 'Ring', 'chapters': ['UndeadRE02', 'UndeadRE02_02']},
    {'code': 'ergp', 'name': '傲慢之赐', 'description': '史诗饰品\n\n+6所有属性\n+18%法术暴击几率\n装备：获得傲慢诅咒，使400范围内附近其他友方单位的攻击力降低15%。\n\n傲慢是文明的崩塌之因。它如同毒蛇盘踞心底，是万恶之源，灼伤灵魂，只留下满目疮痍。', 'slot': 'Ring', 'chapters': ['UndeadRE02_01']},
    {'code': 'ergs', 'name': '怠惰之赐', 'description': '稀有饰品\n\n+7点生命恢复效果\n装备：获得怠惰光环，降低附近敌方单位15%的移动速度。\n\n怠惰，便是不愿付出丝毫努力。信奉此道者，将所有时间都用来休憩和放松。', 'slot': 'Ring', 'chapters': ['UndeadRE02_01']},
    {'code': 'ergw', 'name': '暴怒之赐', 'description': '稀有饰品\n\n+10%致命一击几率\n+15%暴击伤害\n装备：针对佩戴者的攻击有5%几率赋予你无餍之怒效果，攻击速度提升100%，移动速度提升20%，持续4秒。\n\n当怒火攀升为杀意，便会将所有人都视作仇敌。暴怒掌控了心智，眼中便再无他物。', 'slot': 'Ring', 'chapters': ['UndeadRE02_01']},
    {'code': 'erkt', 'name': '肯瑞托法袍', 'description': '精良护甲\n\n+10%技能增强\n+8%魔法抗性\n\n这件紫罗兰色法袍以精制丝绸裁成，胸前绣有肯瑞托的徽记。', 'slot': 'Chest', 'chapters': ['UndeadRE01_05']},
    {'code': 'ernp', 'name': '力量红宝石项链', 'description': '精良饰品\n\n+8点攻击力\n\n这条项链上镶嵌的深红宝石涌动着强大的力量。', 'slot': 'Ring', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'eroe', 'name': '闪避之戒', 'description': '精良饰品\n\n+10%闪避\n\n说来奇怪，它刚好能套在老鼠的脖子上。', 'slot': 'Ring', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'errw', 'name': '鲁因之戒', 'description': '精良饰品\n\n+5%技能增强\n+5%技能速度\n\n大法师安斯雷姆·鲁因在学徒时期常制作附魔戒指来辅助自己施法。', 'slot': 'Ring', 'chapters': ['UndeadRE01_05']},
    {'code': 'ersb', 'name': '鲜血徽记', 'description': '稀有饰品\n\n+15%暴击伤害\n+8%生命窃取\n\n这枚骨戒上雕刻的骷髅正淌着血泪，不断汲取着敌人的生命。', 'slot': 'Ring', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'erse', 'name': '艾露恩之星', 'description': '稀有饰品\n\n+10%技能增强\n+40%法力恢复效果\n\n这颗稀有的宝石在双月的光辉下会绽放出美丽的天蓝色光芒。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'ersf', 'name': '坚毅石戒', 'description': '精良饰品\n\n+2点护甲\n+10%斗志\n\n任凭狂风呼啸，磐石岿然不动。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'ersg', 'name': '圣林之戒', 'description': '稀有饰品\n\n+5点技能伤害\n+150法力值\n装备：近战攻击者会受到自身总攻击力15%的法术伤害反噬。\n\n我们的神圣林地，已遭亵渎！', 'slot': 'Ring', 'chapters': ['UndeadRE02_03']},
    {'code': 'ersk', 'name': '艾卓-尼鲁布典籍', 'description': '稀有饰品\n\n+8%法术暴击几率\n+8点技能伤害\n装备：每隔30秒，你的下一次基础攻击会召唤2只拥有毒素攻击的喷毒蜘蛛，持续12秒。\n\n这部古老典籍记载着艾卓-尼鲁布的秘史，以及蛛魔的作战方略。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'ersm', 'name': '神圣魔法之戒', 'description': '稀有饰品\n\n+4点力量\n+4点智力\n+6点技能伤害\n\n这枚戒指受圣光点化，既能赋予臂膀之力，亦能赐予心神之宁。', 'slot': 'Ring', 'chapters': ['UndeadRE01_02']},
    {'code': 'ersn', 'name': '破法者项链', 'description': '精良饰品\n\n+14%魔法抗性\n\n蕴含防护魔法，可协助破法者对抗敌方巫师。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'esa1', 'name': '圣化胸甲', 'description': '史诗护甲\n\n+5点护甲\n+12%法力值效率\n装备：以圣焰净化你的躯体，每秒对附近敌方单位造成12点伤害。此外，施放法术时恢复25点生命值。\n\n这件护甲蕴含神圣魔法，曾由一位蒙受多重祝福的圣骑士穿戴。', 'slot': 'Chest', 'chapters': ['UndeadRE01_06']},
    {'code': 'esa2', 'name': '圣化护手', 'description': '史诗手套\n\n+5点力量\n+5%技能增强\n装备：你的基础攻击有10%（暴击时15%）几率施放一道圣光波，造成60点法术伤害并使命中的敌人昏迷2秒。\n\n蕴藏于这护手之中的神圣之力，誓要惩戒世间一切邪恶。', 'slot': 'Gloves', 'chapters': ['UndeadRE01_06']},
    {'code': 'esah', 'name': '奥术饥渴法杖', 'description': '精良主手武器\n\n+18%技能增强\n-50%法力恢复效果\n\n持此法杖者皆称其能大幅增强法术威力，但事后会感到精力枯竭。', 'slot': 'Primary', 'chapters': ['UndeadRE01_05']},
    {'code': 'esbs', 'name': '骸骨法杖', 'description': '精良主手武器\n\n+15%技能速度\n+3点生命恢复效果\n\n常由盗取灵魂的通灵师使用。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'escl', 'name': '地穴领主徽记', 'description': '稀有饰品\n\n+12点力量\n\n依照被迫侍奉巫妖王的蛛魔王室的形象所铸。', 'slot': 'Ring', 'chapters': ['UndeadRE03a']},
    {'code': 'escs', 'name': '软木弹射器', 'description': '普通副手武器\n\n+2点攻击力\n+1点敏捷\n\n只要不对着眼睛，拿来玩耍也无伤大雅。', 'slot': 'Offhand', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'esla', 'name': '伐木机左臂', 'description': '稀有副手武器\n\n+2点护甲\n+8%致命一击几率\n装备：你的基础攻击会降低命中敌人的护甲3点，持续5秒。\n\n从一台被毁的地精伐木机上回收而来，锯刃依旧锋利，足以撕裂绝大多数护甲。', 'slot': 'Offhand', 'chapters': ['UndeadRE02_02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'eslo', 'name': '巫妖宝珠', 'description': '稀有副手武器\n\n+50点生命值\n+3点智力\n+5%技能增强\n装备：持有者死亡后，这件物品会在5秒后将其复活，复活后保留500点生命值。该效果有300秒冷却时间。\n\n即便身死，巫妖仍在追寻永生之道。', 'slot': 'Offhand', 'chapters': ['UndeadRE03b']},
    {'code': 'esls', 'name': '洛丹伦盾牌', 'description': '稀有副手武器\n\n+4点护甲\n装备：提升900范围内友方单位的护甲1.5点。\n\n这面盾牌光洁如新，显然曾属于一位恪尽职守的士兵。', 'slot': 'Offhand', 'chapters': ['UndeadRE01']},
    {'code': 'esnm', 'name': '通灵侍僧之履', 'description': '稀有副手武器\n\n+5点智力\n+5%技能汲取\n+5%斗志\n\n这面蕴藏死灵魔法的不洁护盾，既能保护持有者免受魔法侵害，又能汲取附近敌人的生命。', 'slot': 'Offhand', 'chapters': ['UndeadRE01']},
    {'code': 'esns', 'name': '魔枢刺刃', 'description': '稀有副手武器\n\n+4点智力\n+6%攻击速度\n+6%技能速度\n装备：你的基础攻击会使命中的敌方单位冻结3秒。\n\n这柄利刃铸造于魔枢殿堂之中，仍带着诺森德的凛冽寒意。', 'slot': 'Offhand', 'chapters': ['UndeadRE02']},
    {'code': 'esod', 'name': '黑暗权杖', 'description': '史诗副手武器\n\n+15%技能速度\n+15%法术暴击伤害\n装备：获得黑暗光环，为附近友方非英雄单位提升8点攻击力。此外，施放法术时会召唤一名亡灵卫兵为你作战，持续10秒。\n\n黑暗力量的象征，能召唤并激励所有追随这面旗帜的人。', 'slot': 'Offhand', 'chapters': ['UndeadRE02']},
    {'code': 'esos', 'name': '希尔瓦娜斯的图章', 'description': '精良饰品\n\n+5%技能汲取\n+3点敏捷\n\n为纪念游侠将军、致敬女妖之王而打造。', 'slot': 'Ring', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'esot', 'name': '泰坦之盾', 'description': '史诗副手武器\n\n+33%魔法抗性\n\n自黑暗虚空而来的泰坦，重塑了艾泽拉斯，为这片混沌世界带来秩序。', 'slot': 'Offhand', 'chapters': ['UndeadRE03a']},
    {'code': 'essc', 'name': '血色十字军之刃', 'description': '史诗主手武器\n\n+20%攻击速度\n+15%技能速度\n装备：你的基础攻击会为持有者恢复15点生命值。\n\n经圣光祝圣，这把剑在虔信者手中兼具神圣之力与致命威能。', 'slot': 'Primary', 'chapters': ['UndeadRE02_02']},
    {'code': 'essi', 'name': '血色检察官法杖', 'description': '稀有主手武器\n\n+15点攻击力\n+15%技能增强\n\n法杖顶端的神圣圣像，会以神圣之力祝福持有者的攻击和法术。', 'slot': 'Primary', 'chapters': ['UndeadRE02_06']},
    {'code': 'essr', 'name': '粘液戒指', 'description': '精良饰品\n\n+2所有属性\n+5%斗志\n\n这枚戒指表面覆着粘稠的液体，一旦戴上就几乎无法取下。', 'slot': 'Ring', 'chapters': ['UndeadRE02']},
    {'code': 'etee', 'name': '埃德里克的眼睛', 'description': '普通饰品\n（为佩戴者提供一个额外技能）\n\n被遗忘者之瞳\n将这只眼睛的恐怖视线聚焦于敌方目标单位，暴露其弱点。目标将被显形，护甲降低2点，持续30秒。（冷却时间：30秒）\n\n这只眼睛外形怪诞，内里却藏着不凡的魔力。', 'slot': 'Trinket', 'chapters': ['UndeadRE01']},
    {'code': 'etff', 'name': '被遗忘者的利齿', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n食尸\n吞噬周围的一具尸体，每秒治疗20点生命值，最多400点。（冷却时间：30秒）\n\n泛黄的牙齿和萎缩的牙龈，看得出是饿极了，也可能是口腔卫生太差。', 'slot': 'Trinket', 'chapters': ['UndeadRE02']},
    {'code': 'etkj', 'name': '骑士标枪', 'description': '稀有饰品\n（为佩戴者提供一个额外技能）\n\n骑士标枪\n向目标敌方单位投掷锋利长枪，造成270点伤害，并使其昏迷5秒。（冷却时间：20秒）\n\n这支标枪异常锋利、配重均衡，最适合掷向远处的目标。', 'slot': 'Trinket', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'etkt', 'name': '肯瑞托头冠', 'description': '稀有头盔\n\n+8点技能伤害\n+3点智力\n装备：每秒向附近一个随机敌方单位发射一枚魔法弹，造成8点法术伤害。\n\n这顶熠熠生辉的金质头环上镶嵌着一颗菱形紫水晶。', 'slot': 'Head', 'chapters': ['UndeadRE01_05']},
    {'code': 'etmb', 'name': '法力小珠', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n吸收法力\n抽取己方单位的100点法力值，转移给施法者。（冷却时间：20秒）\n\n容器内封存着一颗空置法力宝石，等待注满魔力。', 'slot': 'Trinket', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
    {'code': 'etmi', 'name': '初级洞察护身符', 'description': '普通饰品\n\n+2点智力\n+5%暴击伤害\n\n激战之中，清醒的头脑便是最锋利的刀刃。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'etmp', 'name': '凤凰印记', 'description': '精良饰品\n（为佩戴者提供一个额外技能）\n\n火焰之息\n对敌方单位吐出一股锥形火焰，造成100点法术伤害。（冷却时间：20秒）\n\n这枚印记施放魔法时，会燃起灼人的烈焰。', 'slot': 'Trinket', 'chapters': ['UndeadRE01_05']},
    {'code': 'etnw', 'name': '北风护身符', 'description': '普通饰品\n\n+3点攻击力\n+3%魔法抗性\n\n这枚护符为佩戴者注入诺森德寒风般的冷峻凛冽。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'etom', 'name': '食人魔法师图腾', 'description': '史诗主手武器\n\n+10%技能增强\n+15%法术暴击几率\n装备：每隔30秒，你的下一次基础攻击会召唤一根战斗图腾，持续10秒。该图腾每秒为附近友方单位恢复其最大生命值的2%，并周期性为他们施放嗜血。\n\n食人魔法师潜心钻研能带来战场胜利的法术。', 'slot': 'Primary', 'chapters': ['UndeadRE02_04']},
    {'code': 'eton', 'name': '梦魇护符', 'description': '精良饰品\n\n+5%技能增强\n+3点智力\n装备：你的基础攻击有15%几率使目标沉睡6秒。\n\n这枚受诅咒的护符能引发出佩戴者内心最深的恐惧。', 'slot': 'Ring', 'chapters': ['UndeadRE01']},
    {'code': 'etow', 'name': '意志护符', 'description': '精良饰品\n\n+25%法力恢复效果\n+15%暴击伤害\n\n这枚护符蕴含着宁静的恢复魔法，散发着沉静而坚定的能量光晕。', 'slot': 'Ring', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'eucr', 'name': '幽暗城锁链法袍', 'description': '精良护甲\n\n+5%技能增强\n+10%斗志\n\n采用从都城废墟中回收的布料和金属重新打造而成。', 'slot': 'Chest', 'chapters': ['UndeadRE02', 'UndeadRE03a', 'UndeadRE03b']},
    {'code': 'evow', 'name': '波涛语者法衣', 'description': '稀有护甲\n\n+4点生命恢复效果\n+100%法力恢复效果\n装备：施放法术时恢复附近的最多4个友方单位20点生命值。\n\n能与水元素沟通的萨满掌握着强大的恢复魔法。', 'slot': 'Chest', 'chapters': ['UndeadRE01_05']},
    {'code': 'evsk', 'name': '风暴之王法衣', 'description': '史诗护甲\n\n+5点敏捷\n+10%技能增强\n+15%法术暴击几率\n装备：你施放的法术有10%几率在你所在位置召唤雷暴，在10秒内每隔2秒对附近敌方单位造成50点法术伤害。该效果每10秒仅能触发一次。\n\n为效仿诺森德风暴巨人之王的装束以及他所掌控的力量而打造。', 'slot': 'Chest', 'chapters': ['UndeadRE03a']},
    {'code': 'ewao', 'name': '破旧的冒险者外衣', 'description': '普通护甲\n\n+1所有属性\n+50点生命值\n\n散发着冒险的鲜活气息，又混杂着污浊的恶臭。', 'slot': 'Chest', 'chapters': ['UndeadRE01']},
    {'code': 'ewfb', 'name': '邪牙之刃', 'description': '精良主手武器\n\n+10点攻击力\n+3%生命窃取\n\n这把双刃兵器采用恐怖巨兽的颚骨雕琢而成，一侧布满刃齿。', 'slot': 'Primary', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'ews1', 'name': '破旧钢板甲', 'description': '普通护甲\n\n+2点护甲\n\n尽管锈迹斑斑，这件胸甲仍能提供充足的防护。', 'slot': 'Chest', 'chapters': ['UndeadRE01', 'UndeadRE02']},
    {'code': 'ewwg', 'name': '织网者手套', 'description': '精良手套\n\n+5点敏捷\n\n编织得如蛛网一般精巧细密。', 'slot': 'Gloves', 'chapters': ['UndeadRE01']},
    {'code': 'eymo', 'name': '淤血虫“肥躯”', 'description': '传说主手武器\n\n+20点力量\n+20%攻击速度\n装备：你的基础攻击有1%几率永久提升1点力量。\n\n这只巨型腐尸虫由大药剂师普特雷斯捕获、研究并培育，食欲永无止境。它每进食一次便会愈发庞大，那张啮咬不休的巨口会贪婪地吞噬一切靠近的生物。倘若淤血虫挣脱束缚，便需黑暗游侠出手追捕，赶在它将整片乡村吞噬殆尽之前将其制服。', 'slot': 'Primary', 'chapters': ['UndeadRE02']},
    {'code': 'ezba', 'name': '僵尸手臂', 'description': '普通主手武器\n\n+4点攻击力\n+1%生命窃取\n\n这件小饰物虽粗陋，使用得当的话妙用无穷。', 'slot': 'Primary', 'chapters': ['UndeadRE01']},
    {'code': 'ezgc', 'name': '赞达拉巨人克星', 'description': '史诗主手武器\n\n+5所有属性\n+25%暴击伤害\n装备：你的基础攻击有5%（暴击时12%）几率施放战争践踏，造成50点法术伤害并使附近敌方单位昏迷3秒。对英雄单位的触发几率提升15%。\n\n赞达拉帝国是最古老、最伟大的巨魔文明之一，他们以力量和智慧闻名于世。', 'slot': 'Primary', 'chapters': ['UndeadRE02']},
    {'code': 'hsmm', 'name': '骷髅法师面具', 'description': '普通头盔\n\n+1点护甲\n+25点法力值\n\n从一个结错仇家的骷髅身上而来。', 'slot': 'Head', 'chapters': ['UndeadRE01']},
    {'code': 'rrsl', 'name': '雄狮之心', 'description': '精良护甲\n\n+200点生命值\n+10%斗志\n\n其上雕铸的庄严形象能激发人们的勇气和追求荣耀之心。', 'slot': 'Chest', 'chapters': ['UndeadRE01']},
    {'code': 'rspa', 'name': '达拉然徽记之戒', 'description': '精良饰品\n\n+10%技能增强\n\n戒指上镶嵌的紫水晶保存完好，魔力经久不散。', 'slot': 'Ring', 'chapters': ['UndeadRE03a', 'UndeadRE03b']},
)
