"""Generate matching C/Python native indexes from audited offline evidence."""
import argparse
import hashlib
import json
from pathlib import Path
import pefile
from war3_native_bootstrap_audit import IMAGE_SHA256, TEXT_SHA256


def fnv(data):
    value = 14695981039346656037
    for byte in data:
        value = ((value ^ byte)*1099511628211) & 0xffffffffffffffff
    return value


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--image', type=Path, required=True)
    parser.add_argument('--text', type=Path, required=True)
    parser.add_argument('--registrations', type=Path, required=True)
    args = parser.parse_args()
    image, code = args.image.read_bytes(), args.text.read_bytes()
    if hashlib.sha256(image).hexdigest() != IMAGE_SHA256 or hashlib.sha256(code).hexdigest() != TEXT_SHA256:
        raise ValueError('Unsupported evidence')
    report = json.loads(args.registrations.read_text())
    if report['image_sha256'] != IMAGE_SHA256 or report['captured_text_sha256'] != TEXT_SHA256 or report['conflicts']:
        raise ValueError('Registration evidence mismatch/conflict')
    rows = sorted(report['registrations'].items())
    digest = hashlib.sha256(json.dumps(rows, sort_keys=True).encode()).digest()
    profile_id = int.from_bytes(digest[:4], 'little')
    pe = pefile.PE(data=image, fast_load=True)
    root = Path(__file__).resolve().parents[1]
    lines = ['/* Generated by generate_native_bootstrap_profile.py; do not hand-edit. */',
             f'#define WAR3_BOOTSTRAP_PROFILE_ID 0x{profile_id:08x}u',
             f'#define WAR3_BOOTSTRAP_TIMESTAMP 0x{pe.FILE_HEADER.TimeDateStamp:x}u',
             f'#define WAR3_BOOTSTRAP_IMAGE_SIZE 0x{pe.OPTIONAL_HEADER.SizeOfImage:x}u',
             '#define WAR3_BOOTSTRAP_CONTEXT_RVA 0x30d360u',
             '#define WAR3_BOOTSTRAP_HASH_RVA 0x2e6940u',
             '#define WAR3_BOOTSTRAP_UNIT_RVA 0xa110b0u',
             '#define WAR3_BOOTSTRAP_ITEM_RVA 0xa0dff0u',
             '#define WAR3_BOOTSTRAP_AGENT_RVA 0x31f430u',
             'static const War3BootstrapCodeCheck g_bootstrap_checks[] = {']
    for rva, size in ((0x30d360, 0x7f), (0x2e6940, 64), (0xa110b0, 64), (0xa0dff0, 64), (0x31f430, 64)):
        lines.append(f'    {{0x{rva:x}u, {size}u, 0x{fnv(code[rva-4096:rva-4096+size]):016x}ULL}},')
    lines += ['};', 'static const War3BootstrapNative g_bootstrap_names[] = {']
    for name, record in rows:
        rva = int(record['handler_rva'], 16)
        lines.append(f'    {{"{name}", "{record["signature"]}", 0x{rva:x}u, 0x{fnv(code[rva-4096:rva-4096+64]):016x}ULL}},')
    lines += ['};', '']
    (root/'tools/war3_native_bootstrap_profile.h').write_text('\n'.join(lines), encoding='utf-8')
    (root/'war3_native_profile.py').write_text(
        '# Generated by tools/generate_native_bootstrap_profile.py; do not hand-edit.\n'
        f'PROFILE_ID = 0x{profile_id:08x}\nNATIVE_NAMES = (\n'+
        ''.join(f'    {name!r},\n' for name, _ in rows)+')\n'
        'NATIVE_INDEX = {name: index for index, name in enumerate(NATIVE_NAMES)}\n', encoding='utf-8')
    print(f'Generated {len(rows)} native indexes, profile {profile_id:#x}')


if __name__ == '__main__':
    main()
