"""Generate a fixed Warcraft III 3.0 object catalog from extracted CASC SLK files."""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


RAWCODE_RE = re.compile(r"^[!-~]{4}$")


def _split_slk(line: str) -> list[str]:
    parts: list[str] = []
    start = 0
    quoted = False
    index = 0
    while index < len(line):
        char = line[index]
        if char == '"':
            if quoted and index + 1 < len(line) and line[index + 1] == '"':
                index += 2
                continue
            quoted = not quoted
        elif char == ';' and not quoted:
            parts.append(line[start:index])
            start = index + 1
        index += 1
    parts.append(line[start:])
    return parts


def _cell_value(token: str) -> str:
    value = token[1:] if token.startswith('K') else ''
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        value = value[1:-1].replace('""', '"')
    return value


def read_slk(path: Path) -> list[dict[str, str]]:
    cells: dict[tuple[int, int], str] = {}
    current_x = 0
    current_y = 0
    for raw_line in path.read_text(encoding='utf-8-sig', errors='replace').splitlines():
        if not raw_line.startswith('C;'):
            continue
        x = current_x
        y = current_y
        value: str | None = None
        for token in _split_slk(raw_line)[1:]:
            if token.startswith('X'):
                x = int(token[1:])
            elif token.startswith('Y'):
                y = int(token[1:])
            elif token.startswith('K'):
                value = _cell_value(token)
        current_x = x
        current_y = y
        if value is not None and x > 0 and y > 0:
            cells[(x, y)] = value

    headers = {
        x: value
        for (x, y), value in cells.items()
        if y == 1 and value
    }
    rows: list[dict[str, str]] = []
    for y in sorted({row for _x, row in cells if row > 1}):
        row = {
            headers[x]: value
            for (x, row_index), value in cells.items()
            if row_index == y and x in headers and headers[x]
        }
        if row:
            rows.append(row)
    return rows


def _rawcodes(path: Path, key: str) -> tuple[str, ...]:
    values: list[str] = []
    for row in read_slk(path):
        value = row.get(key, '')
        if RAWCODE_RE.fullmatch(value) and value not in values:
            values.append(value)
    return tuple(values)


def _literal(values: tuple[str, ...]) -> str:
    if not values:
        return '()'
    return '(\n' + '\n'.join(f'    {value!r},' for value in values) + '\n)'


def generate(source_dir: Path, output: Path) -> dict[str, object]:
    sources = {
        'item': (source_dir / 'ItemData.slk', 'itemID'),
        'ability': (source_dir / 'AbilityData.slk', 'code'),
        'unit': (source_dir / 'UnitData.slk', 'unitID'),
    }
    catalogs = {
        name: _rawcodes(path, key)
        for name, (path, key) in sources.items()
    }
    hashes = {
        name: hashlib.sha256(path.read_bytes()).hexdigest()
        for name, (path, _key) in sources.items()
    }
    output.write_text(
        '"""Warcraft III 3.0.0.24268 object rawcodes extracted from CASC.\n'
        'Generated by tools/generate_war3_casc_catalog.py.\n"""\n\n'
        'GAME_BUILD = "3.0.0.24268"\n'
        f'SOURCE_SHA256 = {hashes!r}\n'
        f'CATALOG_COUNTS = { {name: len(values) for name, values in catalogs.items()}!r}\n\n'
        f'ITEM_RAWCODES = {_literal(catalogs["item"])}\n\n'
        f'ABILITY_RAWCODES = {_literal(catalogs["ability"])}\n\n'
        f'UNIT_RAWCODES = {_literal(catalogs["unit"])}\n',
        encoding='ascii',
        newline='\n',
    )
    return {
        'build': '3.0.0.24268',
        'source_sha256': hashes,
        'counts': {name: len(values) for name, values in catalogs.items()},
    }


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f'usage: {Path(argv[0]).name} <extracted-dir> <output.py>', file=sys.stderr)
        return 2
    source_dir = Path(argv[1])
    output = Path(argv[2])
    summary = generate(source_dir, output)
    print(summary)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
