"""Generate the compiled bridge defaults from the same JSON Python consumes."""

from pathlib import Path
import argparse, json, os, tempfile

ROOT = Path(__file__).resolve().parents[1]


def generate():
    import sys
    sys.path.insert(0, str(ROOT))
    from war3_game_profile import load_profile
    profile = load_profile(ROOT / "profiles/3.0.0.24268.json")
    data = profile.to_dict()
    fields = profile.section("bridge_layout")
    lines = [
        "/* Generated by tools/generate_bridge_profile.py. Do not edit. */",
        "#ifndef WAR3_BRIDGE_PROFILE_H",
        "#define WAR3_BRIDGE_PROFILE_H",
        "typedef struct BridgeProfile {",
        "    uint32_t version, size;",
    ]
    lines += ["    uint32_t " + name + ";" for name in fields]
    lines += [
        "} BridgeProfile;",
        "__declspec(dllexport) volatile BridgeProfile bridge_profile = {",
        "    " + str(data["bridge_profile_version"]) + "u, sizeof(BridgeProfile),",
        "    " + ", ".join(hex(v) + "u" for v in fields.values()),
        "};",
        "__declspec(dllexport) const uint32_t bridge_profile_abi[2] = {" + str(data["bridge_profile_version"]) + "u, sizeof(BridgeProfile)};",
        "static void BridgeProfileCopy(volatile BridgeProfile *destination, const volatile BridgeProfile *source) {",
        "    volatile uint32_t *out = (volatile uint32_t *)destination;",
        "    const volatile uint32_t *in = (const volatile uint32_t *)source;",
        "    for (uint32_t i = 0; i < sizeof(BridgeProfile) / sizeof(uint32_t); ++i) out[i] = in[i];",
        "}",
        "#endif",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "tools/war3_bridge_profile.h"
    text = generate()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf8") != text:
            raise SystemExit("Bridge profile header is stale")
    else:
        fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=".profile-")
        with os.fdopen(fd, "w", encoding="utf8", newline="\n") as f:
            f.write(text)
        os.replace(tmp, target)
