/* Generated by tools/generate_bridge_profile.py. Do not edit. */
#ifndef WAR3_BRIDGE_PROFILE_H
#define WAR3_BRIDGE_PROFILE_H
typedef struct BridgeProfile {
    uint32_t version, size;
    uint32_t registry_root_rva;
    uint32_t primary;
    uint32_t alternate;
    uint32_t table_count;
    uint32_t stride;
    uint32_t slot_owner;
    uint32_t owner_handle;
    uint32_t owner_data;
    uint32_t object_handle;
    uint32_t object_rawcode;
    uint32_t unit_attack;
    uint32_t ability_level_tail;
} BridgeProfile;
__declspec(dllexport) volatile BridgeProfile bridge_profile = {
    2u, sizeof(BridgeProfile),
    0x2f807f0u, 0x18u, 0x50u, 0x18u, 0x10u, 0x8u, 0x20u, 0x90u, 0x18u, 0x70u, 0x760u, 0x4bcu
};
__declspec(dllexport) const uint32_t bridge_profile_abi[2] = {2u, sizeof(BridgeProfile)};
#endif
